---
version: "2.0"
services:
  hypersign:
    image: ghcr.io/hypersign-protocol/hid-node:latest
    expose:
      - port: 26657
        as: 26657
        to:
          - global: true
      - port: 1317
        as: 1317
        to:
          - global: true
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 9090
        as: 9090
        to:
          - global: true
    command:
      - bash
      - "-c"
    args:
      - hid-noded start
profiles:
  compute:
    hypersign:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          - size: 150Gi
  placement:
    dcloud:
      pricing:
        hypersign:
          denom: uakt
          amount: 1000
deployment:
  hypersign:
    dcloud:
      profile: hypersign
      count: 1
